document.write("<link href=\"http://creativecommons.org/includes/campaignwidget.css?1.1.0\" rel=\"stylesheet\" type=\"text/css\" />");
document.write("");
document.write("<div id=\"cc_campaign_widget\" class=\"" + cc_widget_size + "\">");
document.write("<div id=\"cc_campaign_widget_bg\"><div id=\"cc_campaign_widget_bg_logo\">");
document.write("<h1 id=\"cc_widget_title\"><span>Creative Commons</span></h1>");
document.write("<p id=\"cc_widget_text\">" + cc_widget_text + "</p>");
document.write("<div id=\"donors\">");
document.write("<strong>Help support Creative Commons</strong><br/>");
document.write("</div>");
document.write("");
document.write("<form method=\"get\" action=\"http://support.creativecommons.org/civicrm/contribute/transact\">");
document.write("");
document.write("$<input id=\"cc_widget_donation\" name=\"donation\" value=\"" + cc_widget_d_amt + "\" size=\"6\" />");
document.write("<input name=\"reset\" value=\"1\" type=\"hidden\" />");
document.write("<input name=\"id\" value=\"1\" type=\"hidden\" />");
document.write("");
document.write("&nbsp;<input type=\"submit\" id=\"cc_widget_donation_btn\" value=\"Donate\" />");
document.write("");
document.write("</form>");
document.write("");
document.write("<div id=\"cc_widget_get\"><a href=\"http://support.creativecommons.org/widget\" id=\"cc_widget_share\">" + cc_widget_share + "</a></div>");
document.write("</div></div>");
document.write("</div>");
document.write("");